payload:
  scalars:
    parent:
      match:
        table_group: scalars
        type: scalar
        details:
          keyed: false
          record_in_processes:
            contains: main
          record_into_store:
            contains: deletion-request
  processes:  # fields under processes are deprecated
    parent:
      scalars:
        match:
          table_group: scalars
          type: scalar
          details:
            keyed: false
            record_in_processes:
              contains: main
            record_into_store:
              contains: deletion-request
