# app ids to replace glean v1 with v2
# needed temporarily because not all apps will be changed at the same time
#- accounts-cirrus
#- burnham
#- experimenter-cirrus
#- firefox-crashreporter
#- firefox-desktop
#- firefox-desktop-background-defaultagent
#- firefox-desktop-background-tasks
#- firefox-desktop-background-update
#- monitor-cirrus
#- mozilla-lockbox
#- mozilla-mach
#- mozillavpn
#- mozillavpn-backend-cirrus
#- mozphab
#- net-thunderbird-android
#- net-thunderbird-android-beta
#- net-thunderbird-android-daily
#- org-mozilla-connect-firefox
#- org-mozilla-fenix
#- org-mozilla-fenix-nightly
#- org-mozilla-fennec-aurora
#- org-mozilla-firefox
#- org-mozilla-firefox-beta
#- org-mozilla-firefox-vpn
#- org-mozilla-firefoxreality
#- org-mozilla-focus
#- org-mozilla-focus-beta
#- org-mozilla-focus-nightly
#- org-mozilla-ios-fennec
#- org-mozilla-ios-firefox
#- org-mozilla-ios-firefoxbeta
#- org-mozilla-ios-firefoxvpn
#- org-mozilla-ios-firefoxvpn-network-extension
#- org-mozilla-ios-focus
#- org-mozilla-ios-klar
#- org-mozilla-ios-lockbox
#- org-mozilla-klar
#- org-mozilla-mozregression
#- org-mozilla-reference-browser
#- org-mozilla-social-nightly
#- org-mozilla-tv-firefox
#- org-mozilla-vrbrowser
#- pine
#- thunderbird-desktop
