# metrics per app or library to exclude from output
# keys can be either the app name (e.g. fenix) which includes all channels or the app id (org-mozilla-firefox)
android-places:
- places_manager.read_query_time
- places_manager.scan_query_time
- places_manager.write_query_time
engine-gecko:
- avif.dav1d_decode_error
- fog.validation.gvsv_audio_stream_init_gvst
- gfx.adapter.primary.device_id_last_seen
- gfx.status.compositor_last_seen
- gfx.status.framebuild_time
- gfx.status.sceneswap_time
- gfx.webrender.render_time
- js.baseline_compile_percentage
- js.bytecode_caching_time
- js.delazification_percentage
- js.execution_percentage
- js.xdr_encode_percentage
- media.audio_init_failure
- performance.time.load_event_end_no_preload
- performance.time.load_event_end_preload
- performance.time.load_event_start_no_preload
- performance.time.load_event_start_preload
engine-gecko-beta:
- avif.dav1d_decode_error
- fog.validation.gvsv_audio_stream_init_gvst
- gfx.adapter.primary.device_id_last_seen
- gfx.status.compositor_last_seen
- gfx.status.framebuild_time
- gfx.status.sceneswap_time
- gfx.webrender.render_time
- js.baseline_compile_percentage
- js.bytecode_caching_time
- js.delazification_percentage
- js.execution_percentage
- js.xdr_encode_percentage
- media.audio_init_failure
- performance.time.load_event_end_no_preload
- performance.time.load_event_end_preload
- performance.time.load_event_start_no_preload
- performance.time.load_event_start_preload
engine-gecko-nightly:
- avif.a1lx
- avif.a1op
- avif.alpha
- avif.aom_decode_error
- avif.bit_depth
- avif.cicp_cp
- avif.cicp_mc
- avif.cicp_tc
- avif.clap
- avif.colr
- avif.dav1d_decode_error
- avif.decode_result
- avif.decoder
- avif.grid
- avif.ipro
- avif.ispe
- avif.lsel
- avif.major_brand
- avif.pasp
- avif.pixi
- avif.sequence
- avif.yuv_color_space
- fog.validation.gvsv_audio_stream_init_gvst
- geckoview.build_id
- geckoview.content_process_lifetime
- geckoview.document_site_origins
- geckoview.page_load_progress_time
- geckoview.page_load_time
- geckoview.page_reload_time
- geckoview.per_document_site_origins
- geckoview.startup_runtime
- geckoview.version
- gfx.adapter.primary.description
- gfx.adapter.primary.device_id
- gfx.adapter.primary.device_id_last_seen
- gfx.adapter.primary.driver_date
- gfx.adapter.primary.driver_files
- gfx.adapter.primary.driver_vendor
- gfx.adapter.primary.driver_version
- gfx.adapter.primary.ram
- gfx.adapter.primary.subsystem_id
- gfx.adapter.primary.vendor_id
- gfx.checkerboard.duration
- gfx.checkerboard.peak_pixel_count
- gfx.checkerboard.potential_duration
- gfx.checkerboard.severity
- gfx.composite_time
- gfx.content.frame_time.from_paint
- gfx.content.frame_time.from_vsync
- gfx.content.frame_time.reason
- gfx.content.frame_time.with_svg
- gfx.content.frame_time.without_resource_upload
- gfx.content.frame_time.without_upload
- gfx.content.full_paint_time
- gfx.content.paint_time
- gfx.display.count
- gfx.display.primary_height
- gfx.display.primary_width
- gfx.feature.webrender
- gfx.scroll_present_latency
- gfx.status.compositor
- gfx.status.compositor_last_seen
- gfx.status.framebuild_time
- gfx.status.headless
- gfx.status.last_compositor_gecko_version
- gfx.status.sceneswap_time
- gfx.webrender.framebuild_time
- gfx.webrender.render_time
- gfx.webrender.scenebuild_time
- gfx.webrender.sceneswap_time
- javascript.gc.compact_time
- javascript.gc.mark_roots_time
- javascript.gc.mark_time
- javascript.gc.minor_time
- javascript.gc.prepare_time
- javascript.gc.slice_time
- javascript.gc.sweep_time
- javascript.gc.total_time
- javascript.pageload.baseline_compile_time
- javascript.pageload.delazification_time
- javascript.pageload.execution_time
- javascript.pageload.gc_time
- javascript.pageload.parse_time
- javascript.pageload.protect_time
- javascript.pageload.xdr_encode_time
- js.baseline_compile_percentage
- js.bytecode_caching_time
- js.delazification_percentage
- js.execution_percentage
- js.xdr_encode_percentage
- media.audio.backend
- media.audio.init_failure
- media.audio_init_failure
- network.cache_hit_time
- network.dns_end
- network.dns_start
- network.first_from_cache
- network.font_download_end
- network.tcp_connection
- network.tls_handshake
- performance.clone.deserialize.items
- performance.clone.deserialize.size
- performance.clone.deserialize.time
- performance.interaction.keypress_present_latency
- performance.interaction.mouseup_click_present_latency
- performance.interaction.tab_switch_composite
- performance.page.non_blank_paint
- performance.page.total_content_page_load
- performance.pageload.dcl
- performance.pageload.dcl_responsestart
- performance.pageload.fcp
- performance.pageload.fcp_responsestart
- performance.pageload.load_time
- performance.pageload.load_time_responsestart
- performance.pageload.req_anim_frame_callback
- performance.responsiveness.req_anim_frame_callback
- performance.time.dom_complete
- performance.time.dom_content_loaded_end
- performance.time.dom_content_loaded_start
- performance.time.dom_interactive
- performance.time.load_event_end
- performance.time.load_event_end_no_preload
- performance.time.load_event_end_preload
- performance.time.load_event_start
- performance.time.load_event_start_no_preload
- performance.time.load_event_start_preload
- performance.time.response_start
fenix:
- contextual_menu.long_press_tapped
- credit_cards.autofill_card
- credit_cards.delete_card
- credit_cards.manual_save
- customize_home.recently_saved
- downloads.downloaded_pdf_open_count
- downloads.pdf_download_count
- engine.kill_background_age
- engine.kill_foreground_age
- engine.tab_kills
- engine_tab.kill_background_age
- engine_tab.kill_foreground_age
- engine_tab.kills
- experiments.metrics.active_experiment
- metrics.activity_state_provider_error
- metrics.credit_cards_autofill_count
- metrics.credit_cards_deleted_count
- metrics.credit_cards_saved_count
- metrics.install_source
- metrics.shared_prefs_uuid
- metrics.syncing_items
- metrics.toolbar_position
- metrics.total_uri_count
- perf.startup.app_on_create_to_glean_init
- perf.startup.app_on_create_to_megazord_init
- perf.startup.app_on_create_to_setup_in_main
- perf.startup.base_bfragment_on_create_view
- perf.startup.base_bfragment_on_view_created
- perf.startup.home_activity_on_create
- perf.startup.home_activity_on_start
- perf.startup.home_fragment_on_create_view
- perf.startup.home_fragment_on_view_created
- play_store_attribution.deferred_deeplink_time
- preferences.open_links_in_a_private_tab
- preferences.open_links_in_app
- preferences.open_links_in_private
- preferences.private_search_suggestions
- preferences.remote_debugging
- preferences.search_bookmarks
- preferences.search_browsing_history
- preferences.search_suggestions_private
- preferences.search_term_groups_enabled
- preferences.show_clipboard_suggestions
- preferences.show_search_shortcuts
- preferences.show_search_suggestions
- preferences.show_voice_search
- preferences.sync
- preferences.telemetry
- preferences.theme
- preferences.toolbar_position
- preferences.tracking_protection
- recent_bookmarks.bookmark_clicked
- recent_bookmarks.recent_bookmarks_count
- recent_bookmarks.show_all_bookmarks
- search.default_engine.submission_url
- search_terms.group_size_distribution
- tab_strip.enabled
- wallpapers.discovered_wallpaper_feature
firefox_desktop:
- browser.link.open_newwindow_restriction
- dap.report_generation_status
- dap.upload_status
- extensions.apis.dnr.evaluate_rules_count_max
- extensions.apis.dnr.evaluate_rules_time
- extensions.apis.dnr.startup_cache_entries
- extensions.apis.dnr.startup_cache_read_size
- extensions.apis.dnr.startup_cache_read_time
- extensions.apis.dnr.startup_cache_write_size
- extensions.apis.dnr.startup_cache_write_time
- extensions.apis.dnr.validate_rules_time
- extensions.startup_cache_load_time
- gecko.build_id
- gecko.version
- ping.centre.send_failures
- ping.centre.send_failures_by_namespace
- ping.centre.send_successes_by_namespace
- private_attribution.database
- private_attribution.measure_conversion
- private_attribution.save_impression
- startup.is_restored_by_macos
- startup.run_from_dmg_install_outcome
firefox_ios:
- app_menu.library
- application_services.bookmark_highlights_visible
- application_services.pocket_stories_visible
- application_services.recent_highlights_visible
- firefox_home_page.cycle_wallpaper_button
- firefox_home_page.history_highlights_view
- firefox_home_page.jump_back_in_section_view
- firefox_home_page.your_library
- inactive_tabs_tray.open_recently_closed_list
- inactive_tabs_tray.open_recently_closed_tab
- onboarding.sync_screen
- onboarding.sync_screen_browse
- onboarding.sync_screen_sign_up
- onboarding.welcome_screen
- onboarding.welcome_screen_close
- onboarding.welcome_screen_next
- onboarding.welcome_screen_sign_in
- onboarding.welcome_screen_sign_up
- page_action_menu.add_to_reading_list
- pocket.open_story
- preferences.block_popups
- preferences.mail_client
- reading_list.mark_read
- reading_list.mark_unread
- sync.open_sync_home_shortcut
- theme.automatic_mode
- theme.automatic_slider_value
- theme.name
- theme.use_system_theme
- top_site.pressed_tile_origin
focus_android:
- nimbus_experiments.nimbus_initial_fetch
- settings_screen.autocomplete_domain_added
- settings_screen.whats_new_tapped
gecko:
- bloburl.resolve_stopped
- browser.ui.proton_enabled
- cert_verifier.cert_trust_evaluation_time
- cookie.banners.click.handle_duration
- cookie.banners.cmp.handle_duration
- data_storage.entries
- data_storage.migration
- dotprint.android_dialog_requested
- dotprint.failure
- dotprint.requested
- extensions.quarantined_domains.listhash
- extensions.quarantined_domains.listsize
- extensions.quarantined_domains.remotehash
- extensions.timing.storage_local_get_json
- extensions.timing.storage_local_set_json
- fog.validation.gvsv_audio_stream_init
- fog.validation.gvsv_audio_stream_init_gecko
- fog.validation.gvsv_composite_time
- fog.validation.gvsv_number_of_unique_site_origins_all_tabs
- fog.validation.gvsv_primary_height
- fog.validation.gvsv_primary_width
- fog.validation.some_object
- geckoview.validation.build_id
- geckoview.validation.version
- gifft.validation.main_ping_assembling
- ipc.received_messages.content_background
- ipc.received_messages.content_foreground
- ipc.received_messages.gpu_process
- ipc.received_messages.parent_active
- ipc.received_messages.parent_inactive
- ipc.sent_messages.content_background
- ipc.sent_messages.content_foreground
- ipc.sent_messages.gpu_process
- ipc.sent_messages.parent_active
- ipc.sent_messages.parent_inactive
- netwerk.early_hints
- netwerk.eh_link_type
- netwerk.eh_response_version
- network.data_size_pb_per_type
- network.data_size_per_type
- network.open_to_transaction_pending
- networking.http_content_html5parser_ondatafinished_to_onstop_delay_negative
- networking.http_content_ondatafinished_to_onstop_delay_negative
- networking.https_upgrade_with_https_rr
- networking.speculative_connection_outcome
- oskeystore.self_test
- performance.pageload.eh_fcp_preconnect
- performance.pageload.eh_fcp_preconnect_preload_with_eh
- performance.pageload.eh_fcp_preconnect_preload_without_eh
- performance.pageload.eh_fcp_preload_with_eh
- performance.pageload.eh_fcp_preload_without_eh
- pkcs11.built_in_roots_module
- pkcs11.nss_cert_db
- rtcrtpsender.setparameters.blame_length_changed
- rtcrtpsender.setparameters.blame_no_getparameters
- rtcrtpsender.setparameters.blame_no_transactionid
- rtcrtpsender.setparameters.blame_stale_transactionid
- rtcrtpsender.setparameters.warn_rid_changed
- rtcrtpsender.setparameters.warn_stale_transactionid
- use.counter.css.doc.css_align_tracks
- use.counter.css.doc.css_inset_area
- use.counter.css.doc.css_justify_tracks
- use.counter.css.doc.css_position_try_options
- use.counter.css.doc.css_user_find
- use.counter.css.doc.webkit_font_smoothing
- use.counter.css.page.css_align_tracks
- use.counter.css.page.css_inset_area
- use.counter.css.page.css_justify_tracks
- use.counter.css.page.css_position_try_options
- use.counter.css.page.css_user_find
- use.counter.css.page.webkit_font_smoothing
- use.counter.deprecated_ops.doc.is_external_ctap2_security_key_supported
- use.counter.deprecated_ops.doc.mutation_event
- use.counter.deprecated_ops.page.is_external_ctap2_security_key_supported
- use.counter.deprecated_ops.page.mutation_event
- use.counter.doc.js_late_weekday
- use.counter.doc.onbounce
- use.counter.doc.onfinish
- use.counter.doc.onstart
- use.counter.error.unknown_counter
- use.counter.page.js_late_weekday
- use.counter.page.onbounce
- use.counter.page.onfinish
- use.counter.page.onstart
glean-android:
- glean.core.migration.successful
- glean.error.preinit_tasks_timeout
- glean.validation.app_forceclosed_count
- glean.validation.baseline_ping_count
glean-core:
- baseline - glean.baseline.locale
- baseline,glean.validation.first_run_hour
- glean.error.preinit_tasks_timeout
- glean.time.invalid_timezone_offset
- ping_reason
klar_android:
- nimbus_experiments.nimbus_initial_fetch
- settings_screen.autocomplete_domain_added
- settings_screen.whats_new_tapped
logins-store:
- logins_store.migration_errors
- logins_store.migration_num_failed
- logins_store.migration_num_processed
- logins_store.migration_num_succeeded
- logins_store.migration_total_duration
- logins_store.read_query_time
- logins_store.unlock_count
- logins_store.unlock_error_count
- logins_store.unlock_time
- logins_store.write_query_time
pine:
- browser.link.open_newwindow_restriction
- extensions.apis.dnr.evaluate_rules_count_max
- extensions.apis.dnr.evaluate_rules_time
- extensions.apis.dnr.startup_cache_entries
- extensions.apis.dnr.startup_cache_read_size
- extensions.apis.dnr.startup_cache_read_time
- extensions.apis.dnr.startup_cache_write_size
- extensions.apis.dnr.startup_cache_write_time
- extensions.apis.dnr.validate_rules_time
- extensions.startup_cache_load_time
- gecko.build_id
- gecko.version
- ping.centre.send_failures
- ping.centre.send_failures_by_namespace
- ping.centre.send_successes_by_namespace
- startup.run_from_dmg_install_outcome
